# Importamos librerias

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Entender archivos

In [2]:
train_data = pd.read_csv('train.csv')
train_data.head()

,Unnamed: 0,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,class
0,5249,f,y,y,f,f,f,c,b,g,...,p,b,p,w,o,l,h,y,g,p
1,5781,x,s,p,t,n,f,c,b,e,...,e,w,p,w,t,e,w,c,w,e
2,7586,b,s,g,f,n,f,w,b,w,...,w,w,p,w,t,p,w,s,g,e
3,6181,f,s,n,f,s,f,c,n,b,...,p,w,p,w,o,e,w,v,d,p
4,7338,k,y,n,f,f,f,c,n,b,...,p,p,p,w,o,e,w,v,p,p

In [3]:
test_data = pd.read_csv('test.csv')
test_data.head()

,Unnamed: 0,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,4632,x,y,g,f,f,f,c,b,p,...,k,p,n,p,w,o,l,h,y,d
1,3444,x,s,w,f,c,f,c,n,u,...,s,w,w,p,w,o,p,n,s,d
2,1209,x,f,w,f,n,f,w,b,p,...,s,w,w,p,w,o,e,n,s,g
3,6880,f,s,e,f,f,f,c,n,b,...,s,w,w,p,w,o,e,w,v,p
4,4542,x,f,y,f,f,f,c,b,g,...,k,p,n,p,w,o,l,h,y,g

In [4]:
train_data.shape, test_data.shape

((6499, 24), (1625, 23))

In [5]:
train_data.info()
# print('-'*80)
# test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6499 entries, 0 to 6498
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                6499 non-null   int64
 1   cap-shape                 6499 non-null   object
 2   cap-surface               6499 non-null   object
 3   cap-color                 6499 non-null   object
 4   bruises                   6499 non-null   object
 5   odor                      6499 non-null   object
 6   gill-attachment           6499 non-null   object
 7   gill-spacing              6499 non-null   object
 8   gill-size                 6499 non-null   object
 9   gill-color                6499 non-null   object
 10  stalk-shape               6499 non-null   object
 11  stalk-root                6499 non-null   object
 12  stalk-surface-above-ring  6499 non-null   object
 13  stalk-surface-below-ring  6499 non-null   object
 14  stalk-color-above-ring    6499 non-null   object
 15  stalk-color-below-ring    6499 non-null   object
 16  veil-type                 6499 non-null   object
 17  veil-color                6499 non-null   object
 18  ring-number               6499 non-null   object
 19  ring-type                 6499 non-null   object
 20  spore-print-color         6499 non-null   object
 21  population                6499 non-null   object
 22  habitat                   6499 non-null   object
 23  class                     6499 non-null   object
dtypes: int64(1), object(23)
memory usage: 1.2+ MB

In [6]:
# # train_data.isna().sum()
# print('-'*80)
# test_data.isna().sum()

In [7]:
train_data.describe()

        Unnamed: 0
count  6499.000000
mean   4056.284198
std    2341.698691
min       0.000000
25%    2047.500000
50%    4078.000000
75%    6073.500000
max    8123.000000

In [8]:
for col in train_data.columns:
    print(f"{col}: {train_data[col].nunique()} valores Ãºnicos")

Unnamed: 0: 6499 valores Ãºnicos
cap-shape: 6 valores Ãºnicos
cap-surface: 4 valores Ãºnicos
cap-color: 10 valores Ãºnicos
bruises: 2 valores Ãºnicos
odor: 9 valores Ãºnicos
gill-attachment: 2 valores Ãºnicos
gill-spacing: 2 valores Ãºnicos
gill-size: 2 valores Ãºnicos
gill-color: 12 valores Ãºnicos
stalk-shape: 2 valores Ãºnicos
stalk-root: 5 valores Ãºnicos
stalk-surface-above-ring: 4 valores Ãºnicos
stalk-surface-below-ring: 4 valores Ãºnicos
stalk-color-above-ring: 9 valores Ãºnicos
stalk-color-below-ring: 9 valores Ãºnicos
veil-type: 1 valores Ãºnicos
veil-color: 4 valores Ãºnicos
ring-number: 3 valores Ãºnicos
ring-type: 5 valores Ãºnicos
spore-print-color: 9 valores Ãºnicos
population: 6 valores Ãºnicos
habitat: 7 valores Ãºnicos
class: 2 valores Ãºnicos

In [9]:
train_data.duplicated().sum()

0

In [10]:
numeric_columns = train_data.select_dtypes(include=['number'])
numeric_column_names = numeric_columns.columns.tolist()
print("Numeric Column Names:", numeric_column_names)

Numeric Column Names: ['Unnamed: 0']